### ISSUE TITLE
Kubefed 计划归档

### ISSUE THREAD

**Issue by magichan** [rootsongjc/cloud-native-library#91]
根据 https://groups.google.com/g/kubernetes-sig-multicluster/c/lciAVj-_ShE 中的告知，Kubefed 已经计划归档了，

是否方便在 https://lib.jimmysong.io/kubernetes-handbook/multi-cluster/federation/ 内容中，对 federation 现状j进行说明。

**Comment by rootsongjc** [comment]
好的，已更新，谢谢。
